# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f81508840281a7143f79890e1af6357f27e9ea92f2dee66bf73be919a726fad02706db568146dc2ef5135a1a6e9bb75be1c15045a5f8da5bdaeec94d56830584

test:
  secret_key_base: 74a3eef3a5ba41ab3f8f373d9f183294ff0a68ed409d2f5392899ee09ae8b44ba42b9d4883f0f84cdf5f0182ee8299ab1e060ea775c6c165acb79a69adaf476c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
